# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ad56c672b49648166ad2edde1119ed527b674b11547870c78a4dc0f64a57157621ff8e47e1fb7ae4223634db11e83c9b11c4055b6c4d8339ac015ccd633ef2c

test:
  secret_key_base: c59c8ef24abb343eaa8ec27f10445a73567224bf11261f4339e0dd42cad33cee4f26fcf283728279415380dd98cbf5fc892f6c6c2d763ac3c9c20b53677f3e83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
